# https://github.com/vouch/vouch-proxy/blob/master/config/config.yml_example
vouch:
  # valid domains that the jwt cookies can be set into
  # the callback_urls will be to these domains
  domains:
  - 172.17.0.1:88    # the Nginx site for doing authentication via Vouch proxy
  - 172.17.0.1:9090  # the Vouch proxy self
  - 172.17.0.1:8086  # the Keycloak server
  - 172.17.0.1:8903  # the Nexus3 server
  - example.com    # the user's email domain

  headers:
    # claims - a list of claims that will be stored in the JWT and passed down to applications via headers
    # By default claims are sent down as headers with a prefix of X-Vouch-IdP-Claims-ClaimKey
    # Only when a claim is found in the user's info will the header exist.
    # This is optional. These are case sensitive.
    claims:
    # Access http://172.17.0.1:8086/auth/realms/default/.well-known/openid-configuration to find the supported claims
    - groups
    - preferred_username # which means the username (not email)
    # these will result in two headers being passed back to nginx
    # X-Vouch-IdP-Claims-groups
    # X-Vouch-IdP-Claims-preferred_username

    # accesstoken - Pass the user's access token from the provider.
    # This is useful if you need to pass the IdP token to a downstream application.
    # This is optional.
    accesstoken: X-Vouch-IdP-AccessToken
  # in order to prevent redirection attacks all redirected URLs to /logout must be specified
  # the URL must still be passed to Vouch Proxy as https://vouch.yourdomain.com/logout?url=${ONE OF THE URLS BELOW}
  post_logout_redirect_uris:
    - http://172.17.0.1:8086/auth/realms/default/protocol/openid-connect/logout

oauth:
  # Generic OpenID Connect
  provider: oidc
  client_id: nexus3
  client_secret: af5e2fba-ccd7-4bf8-a3d8-190dd203127b
  auth_url: http://172.17.0.1:8086/auth/realms/default/protocol/openid-connect/auth
  token_url: http://172.17.0.1:8086/auth/realms/default/protocol/openid-connect/token
  user_info_url: http://172.17.0.1:8086/auth/realms/default/protocol/openid-connect/userinfo
  end_session_endpoint: http://172.17.0.1:8086/auth/realms/default/protocol/openid-connect/logout
  scopes:
  - openid
  - email
  - profile
  callback_url: http://172.17.0.1:9090/auth
